### ISSUE TITLE
Socratic Seminar 07 (2024-03-30) Topic Collection

### ISSUE THREAD

**Issue by okjodom** [BitDevsNBO/bitdevsnbo.org#21]
Please comment with a link to topics you want to share or discuss on our next BitDevs meetup.

@okjodom and @munjesi are looking to host this on the 30th of March, 2024

**Comment by isaack-njama** [comment]
We haven't had any discussion on mining or the protocols involved in mining. I think `StratumV2` would be a great way to kick this off!

> Please comment with a link to topics you want to share or discuss on our next BitDevs meetup.
> 
> @okjodom and @munjesi are looking to host this on the 30th of March, 2024

**Comment by okjodom** [comment]
> We haven't had any discussion on mining or the protocols involved in mining. I think `StratumV2` would be a great way to kick this off!

Fair enough. However, I'd want us to have (built) stronger mining expertise before we dig into the protocols, development and current application of SV2

**Comment by isaack-njama** [comment]
> > We haven't had any discussion on mining or the protocols involved in mining. I think `StratumV2` would be a great way to kick this off!
> 
> Fair enough. However, I'd want us to have (built) stronger mining expertise before we dig into the protocols, development and current application of SV2

Sounds good, what do you have in mind?

**Comment by okjodom** [comment]
nACK
