### ISSUE TITLE
Socratic Seminar 8 : Topic Collection

### ISSUE THREAD

**Issue by okjodom** [BitDevsNBO/bitdevsnbo.org#25]
Collect topics for the next meetup
Date: Jun 29th 2024

**Announcements**

- We have moved from Meetup to Luma

**Suggested Topics and Developments**

## Bitcoin
-  [Silent Payments](https://silentpayments.xyz)
- [BIP352: PSBT support for Silent Payments](https://delvingbitcoin.org/t/bip352-psbt-support/877)
- [A new BIP for Miniscript](https://github.com/achow101/bips/blob/miniscript/bip-miniscript.md)

## Mining
- [TIDES rewards scheme for pooled mining](https://bitcoin.stackexchange.com/questions/120719/how-does-ocean-s-tides-payout-scheme-work)
-  [SV2 Protocol Extension: Share Accounting + Accountability](https://github.com/stratum-mining/sv2-spec/discussions/76#discussioncomment-9472619)
-  

## Lightning
- [Upgrading Existing Lightning Channels](https://delvingbitcoin.org/t/upgrading-existing-lightning-channels/881)
- [Stable Channels - peer-to-peer dollar balances on Lightning](https://delvingbitcoin.org/t/stable-channels-peer-to-peer-dollar-balances-on-lightning/875)
- [Coinbase adds Lightning support](https://www.coinbase.com/blog/coinbase-integrates-bitcoins-lightning-network-in-partnership-with)

## Ecash
- [Ecash TIDES using Cashu and Stratum v2](https://delvingbitcoin.org/t/ecash-tides-using-cashu-and-stratum-v2/870)
-  [Private Fedimint Federations](https://github.com/fedimint/fedimint/pull/5322)

## Other Bitcoin Tech
- [Pushtx for broadcasting transactions](https://github.com/alfred-hodler/pushtx)
- [BitEscrow API: Tooling for building Bitcoin Escrows](https://github.com/BitEscrow/escrow-core) 
- [Sentrum Watch only bitcoin wallet](https://github.com/sommerfelddev/sentrum)
- 

## Extras
- [Coinbase integrates Bitcoin’s Lightning Network in partnership with Lightspark](https://www.coinbase.com/blog/coinbase-integrates-bitcoins-lightning-network-in-partnership-with)

**Comment by okjodom** [comment]
Comment below with suggestions of what you'd like to have covered at the next Bitdevs

**Comment by okjodom** [comment]
- ecash: [mutiny announces harbor](https://blog.mutinywallet.com/harbor/)
- ecash: [the big ecash debate](https://x.com/sethforprivacy/status/1796250854674124875?t=8CM-Y1-lGi3OweXPN32aNg&s=19)

**Comment by okjodom** [comment]
Other tech: [launch of ArkLabs](https://blog.arklabs.to/introducing-ark-labs-a-new-venture-to-bring-seamless-and-scalable-payments-to-bitcoin-811388c0001b)

**Comment by okjodom** [comment]
bitcoin: [open source Volt](https://github.com/Zero-1729/volt)

**Comment by statusquont** [comment]
Hedgehog: https://x.com/super_testnet/status/1798300754698293441

**Comment by SharonMurugi** [comment]
Launch of [Volt Wallet](https://github.com/Zero-1729/volt) and other technical topics from Oslo Freedom Forum.

**Comment by SharonMurugi** [comment]
Launch of [LND 0.18](https://lightning.engineering/posts/2024-05-30-lnd-0.18-launch/)

**Comment by okjodom** [comment]
Rescan blockchain for double spend? https://x.com/realtbast/status/1801274164902277324?t=57lWRdWxrAbk8UX0Vm9GQg&s=19

**Comment by okjodom** [comment]
Chaincode launches rust for bitcoiners : https://x.com/ChaincodeLabs/status/1801301879361609734?t=z7B3qqABSDvz3d_FSLxAnQ&s=19

**Comment by okjodom** [comment]
Lightning: [Bolt 12 website is now fresher!](https://bolt12.org/)

**Comment by statusquont** [comment]
Are 12 word seeds (private keys) enough? Is 24 overkill?

https://twitter.com/super_testnet/status/1803123484274598049

**Comment by statusquont** [comment]
> Are 12 word seeds (private keys) enough? Is 24 overkill?
> 
> https://twitter.com/super_testnet/status/1803123484274598049

Follow-up from Wei Dai! https://x.com/_weidai/status/1803257402457989213
Not going to pretend I understand. :(

**Comment by okjodom** [comment]
Bitcoin: Brollups! https://x.com/brqgoo/status/1803973553458425997?t=RjhZ9-2sSXql1kPOwc07Ww&s=19

**Comment by okjodom** [comment]
Lighting: [LSPS 1 improvements landed](https://github.com/BitcoinAndLightningLayerSpecs/lsp/pull/101)

**Comment by okjodom** [comment]
Lightning: [Bolt 12 Playground](https://strike.me/blog/bolt12-playground/)

**Comment by statusquont** [comment]
Comparing ecash and statecoin:
https://x.com/1440000bytes/status/1805112962941653159

**Comment by okjodom** [comment]
Suggested topics have been moved to #26
