### ISSUE TITLE
Topic suggestions for next seminar

### ISSUE THREAD

**Issue by okjodom** [BitDevsNBO/bitdevsnbo.org#9]
You can comment on this issue to suggest a topic for the next [**BitDevsNBO**](https://www.bitdevsnbo.org/) seminar

**Comment by vladimirfomene** [comment]
@okjodom thanks for opening this. We are starting the study group this week. We are planning a physical meetup every two weeks of the study group. The idea was to dedicate this meetups to Q&A about chapters we just read. I'm thinking we can have guest speakers for these physical events.

**Comment by okjodom** [comment]
Excellent plan!

Now, I'll keep this issue open, to be closed when we post speaker / topic lineup for the next physical meetup

**Comment by vladimirfomene** [comment]
These are the topics for the next meetup on March 18th:
Address Encoding: Base58, Bech32, Bech32m
Bitcoin digital signature schemes: ECDSA, Schnorr Signatures
Introduction to Fedimint Custody Protocol
Designing a bitcoin/Lightning wallet/Introduction to Bitcoin design philosophy
